name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go  environment
      uses: actions/setup-go@v5.0.0
      with:
        go-version-file: ./go.mod 

    - name: Run unit tests (without WSL)
      run: make unit-test
